import test from 'node:test';
import assert from 'node:assert/strict';
import {mockProfile} from '../src/data/mockProfile.js';
import {mockResult} from '../src/data/mockResult.js';
import {validateProfile} from '../src/types/contracts.js';
import {calculatePlan,sendIntakeMessage} from '../src/services/planService.js';
test('contract fixture is complete and invalid values are rejected',()=>{assert.deepEqual(validateProfile(mockProfile),[]);for(const annualIncome of [undefined,NaN,-1])assert.ok(validateProfile({...mockProfile,annualIncome}).includes('Annual income'));assert.ok(validateProfile({...mockProfile,childrenAges:[NaN]}).length);});
test('profile edits cannot silently alter the mock coverage result',async()=>{const response=await calculatePlan({...mockProfile,annualIncome:123456});assert.equal(response.source,'mock');assert.deepEqual(response.result,mockResult);response.result.breakdown.pop();assert.equal(mockResult.breakdown.length,5);});
test('demo does not extract values from natural language',async()=>{const response=await sendIntakeMessage({profile:mockProfile,questionIndex:0,message:'I earn $9 million'});assert.equal(response.profile.annualIncome,75000);assert.equal(response.source,'mock');});
test('invalid profile is rejected by adapter',async()=>{await assert.rejects(calculatePlan({...mockProfile,mortgageBalance:-10}),/Mortgage balance/)});
